---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3fs-minio
  namespace: s3fs-ns
spec: 
  selector:
    matchLabels:
      app: s3fs-minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: s3fs-minio
    spec:
      hostAliases:
      - ip: "131.154.162.124"
        hostnames:
        - "iam-indigo.cr.cnaf.infn.it"
      volumes:
      - name: trust
        emptyDir: {}
      - name: dev-fuse
        hostPath:
          path: /dev/fuse
      initContainers:
      - name: ca-bundle
        image: "alpine"
        command: [sh, -c]
        args:
          - cd /tmp &&
            wget 'http://repository.egi.eu/sw/production/cas/1/current/tgz/' &&
            mkdir tgz && mkdir certificates &&
            for tgz in $(cat index.html | awk -F'"' '{print $2}' | grep tar.gz);
            do wget http://repository.egi.eu/sw/production/cas/1/current/tgz/$tgz -O tgz/$tgz;
            done && for tgz in $(ls tgz/);
            do tar xzf tgz/$tgz --strip-components=1 -C certificates/; done &&
            for f in $(find certificates/ -type f -name '*.pem'); 
            do cat $f >> certs/ca-certificates.crt; done &&
            wget 'https://crt.sh/?d=2475254782' -O certs/geant-ov-rsa-ca.crt &&
            cat certs/geant-ov-rsa-ca.crt >> certs/ca-certificates.crt
        volumeMounts:
        - name: trust
          mountPath: /tmp/certs
      containers:
      - name: s3fs-minio
        image: ffornari/s3fs-oidc-vault-minio
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - eval $(oidc-agent-service use) &&
            oidc-gen --scope-all
            --confirm-default
            --iss=https://iam-indigo.cr.cnaf.infn.it/
            $OIDC_CLIENT_NAME &&
            s3fs ffornari /home/docker/mnt/minio
            -o use_path_request_style
            -o url=https://$MINIO_HOST
            -o no_check_certificate
            -o credlib=liboidc-vault-minio.so
            -o credlib_opts=Info -f
        env:
        - name: OIDC_CLIENT_NAME
          value: "s3fs-minio-client"
        - name: OIDC_ENCRYPTION_PW
          valueFrom:
            secretKeyRef:
              name: oidc-secret
              key: OIDC_ENCRYPTION_PW
        - name: MINIO_HOST
          value: "minio-api-minio-ns.apps.cnsa.cr.cnaf.infn.it"
        - name: VAULT_HOST
          value: "vault-minio-ns.apps.cnsa.cr.cnaf.infn.it"
        - name: VAULT_PORT
          value: "443"
        - name: VAULT_ROLE
          value: "indigo"
        - name: VAULT_TLS_ENABLE
          value: "true"
        - name: VAULT_TLS_VERIFY
          value: "false"
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
          privileged: true
        volumeMounts:
        - mountPath: /dev/fuse
          name: dev-fuse
        - mountPath: /etc/ssl/certs
          name: trust
          readOnly: true
